import { readFile, writeFile, mkdir, readdir, stat, unlink } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import vm from 'node:vm';

export const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const generatedMarker = '<!-- Generated by scripts/build.mjs -->';
const xmlEscape = (value) => String(value).replace(/[&<>"']/g, (character) => ({
  '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&apos;',
})[character]);

export function plainText(html) {
  const entities = { amp: '&', lt: '<', gt: '>', quot: '"', apos: "'", nbsp: ' ', ndash: '-', mdash: '-', hellip: '...' };
  return String(html)
    .replace(/<(script|style)\b[^>]*>[\s\S]*?<\/\1>/gi, ' ')
    .replace(/<!--[\s\S]*?-->/g, ' ')
    .replace(/<[^>]*>/g, ' ')
    .replace(/&(#x[\da-f]+|#\d+|[a-z]+);/gi, (entity, name) => {
      if (name[0] !== '#') return entities[name.toLowerCase()] ?? entity;
      const point = name[1].toLowerCase() === 'x' ? Number.parseInt(name.slice(2), 16) : Number(name.slice(1));
      return point > 0 && point <= 0x10ffff && !(point >= 0xd800 && point <= 0xdfff) ? String.fromCodePoint(point) : ' ';
    })
    .replace(/\s+/g, ' ')
    .trim();
}

function assertText(value, label) {
  if (typeof value !== 'string' || !value.trim()) throw new Error(`${label} must be a nonempty string.`);
}

function assertSegment(value, label) {
  assertText(value, label);
  if (value === '.' || value === '..' || /[<>:"/\\|?*\u0000-\u001f%#]/.test(value) || /[. ]$/.test(value) || /^(con|prn|aux|nul|com\d|lpt\d)(\.|$)/i.test(value)) {
    throw new Error(`${label} cannot be used in a static URL: ${value}`);
  }
}

function assertDate(value, label) {
  if (typeof value !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(value)) throw new Error(`${label} must use YYYY-MM-DD.`);
  const date = new Date(`${value}T00:00:00Z`);
  if (!Number.isFinite(date.getTime()) || date.toISOString().slice(0, 10) !== value) throw new Error(`${label} is not a real date: ${value}`);
}

export function insideRoot(root, relativeFile) {
  const resolved = path.resolve(root, relativeFile);
  const relative = path.relative(root, resolved);
  if (relative.startsWith(`..${path.sep}`) || relative === '..' || path.isAbsolute(relative)) throw new Error(`Path escapes the site root: ${relativeFile}`);
  return resolved;
}

export async function loadContent(root = projectRoot) {
  const source = await readFile(path.join(root, 'js/content.js'), 'utf8');
  const sandbox = vm.createContext({ window: {} }, { codeGeneration: { strings: false, wasm: false } });
  new vm.Script(source, { filename: 'js/content.js' }).runInContext(sandbox, { timeout: 1000 });
  const data = JSON.parse(JSON.stringify(sandbox.window.BLOG_DATA));
  if (!data?.site || !Array.isArray(data.posts) || !data.posts.length) throw new Error('js/content.js must define window.BLOG_DATA with a site and posts.');
  const ids = new Set();
  for (const post of data.posts) {
    if (typeof post.id !== 'string' || !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(post.id)) throw new Error(`Invalid post ID: ${post.id}`);
    if (ids.has(post.id)) throw new Error(`Duplicate post ID: ${post.id}`);
    ids.add(post.id);
    for (const field of ['title', 'excerpt', 'body', 'cover']) assertText(post[field], `${post.id}.${field}`);
    if (!plainText(post.body)) throw new Error(`${post.id}.body contains no readable content.`);
    assertDate(post.date, `${post.id}.date`);
    if (post.updated) {
      assertDate(post.updated, `${post.id}.updated`);
      if (post.updated < post.date) throw new Error(`${post.id}.updated precedes its publication date.`);
    }
    assertSegment(post.category, `${post.id}.category`);
    if (!Array.isArray(post.tags) || !post.tags.length) throw new Error(`${post.id}.tags must be a nonempty array.`);
    for (const tag of post.tags) assertSegment(tag, `${post.id}.tag`);
    if (!/^images\/[\w\-./]+\.(?:avif|gif|jpe?g|png|svg|webp)$/i.test(post.cover)) throw new Error(`${post.id}.cover must name a local image.`);
    const cover = await stat(insideRoot(root, post.cover)).catch(() => null);
    if (!cover?.isFile()) throw new Error(`${post.id}.cover is missing: ${post.cover}`);
  }
  data.posts.sort((a, b) => b.date.localeCompare(a.date) || a.id.localeCompare(b.id));
  data.site = { ...data.site, name: 'SLLYING', description: '\u5199\u4ee3\u7801\uff0c\u4e5f\u6536\u85cf\u5e7b\u60f3\u3002' };
  return data;
}

export async function resolveSiteUrl(site, root = projectRoot, configured = process.env.SITE_URL) {
  let value = configured || site.url || site.origin;
  if (!value) {
    const oldFeed = await readFile(path.join(root, 'feed.xml'), 'utf8').catch(() => '');
    value = oldFeed.match(/<channel>[\s\S]*?<link>\s*(https?:\/\/[^<]+)\s*<\/link>/i)?.[1];
  }
  const previewOnly = !value || /^https?:\/\/(?:localhost|127\.0\.0\.1)(?::\d+)?\//i.test(value);
  const url = new URL(value || 'http://localhost:4173/');
  if (!['http:', 'https:'].includes(url.protocol) || url.username || url.password || url.search || url.hash) throw new Error('SITE_URL must be an HTTP(S) site URL without credentials, query, or fragment.');
  if (!url.pathname.endsWith('/')) url.pathname += '/';
  return { url: url.href, previewOnly };
}

export function baseFor(file) {
  const relative = path.posix.relative(path.posix.dirname(file), '.');
  return relative ? `${relative}/` : './';
}

async function htmlFiles(root, directory) {
  const entries = await readdir(insideRoot(root, directory), { withFileTypes: true }).catch((error) => {
    if (error.code === 'ENOENT') return [];
    throw error;
  });
  const files = [];
  for (const entry of entries) {
    if (entry.name.startsWith('.') || entry.isSymbolicLink()) continue;
    const file = path.posix.join(directory, entry.name);
    if (entry.isDirectory()) files.push(...await htmlFiles(root, file));
    else if (entry.isFile() && entry.name.endsWith('.html')) files.push(file);
  }
  return files;
}

export async function discoverLegacyRoutes(root = projectRoot) {
  const entries = await readdir(root, { withFileTypes: true });
  const directories = entries.filter((entry) => entry.isDirectory() && /^\d{4}$/.test(entry.name)).map((entry) => entry.name);
  const posts = [];
  for (const directory of directories) {
    for (const file of await htmlFiles(root, directory)) {
      const html = await readFile(insideRoot(root, file), 'utf8');
      const destination = html.match(/content=["']\s*0\s*;\s*url=([^"']+)["']/i)?.[1];
      if (!destination) throw new Error(`Legacy article has no migration destination: ${file}`);
      const url = new URL(destination.replaceAll('&amp;', '&'), `https://legacy.invalid/${file}`);
      const id = url.searchParams.get('post') || url.pathname.match(/\/posts\/([^/]+)\/(?:index\.html)?$/)?.[1];
      if (!id) throw new Error(`Legacy article destination is not recognized: ${file}`);
      posts.push({ file, id: decodeURIComponent(id) });
    }
  }
  return {
    posts,
    archives: await htmlFiles(root, 'archives'),
    categories: await htmlFiles(root, 'categories'),
    tags: await htmlFiles(root, 'tags'),
  };
}

export function createRoutes(posts, legacy = { posts: [], archives: [], categories: [], tags: [] }) {
  const routes = new Map();
  const add = (file, context) => routes.set(file, { file, ...context });
  const categories = [...new Set(posts.map((post) => post.category))].sort((a, b) => a.localeCompare(b, 'zh-CN'));
  const tags = [...new Set(posts.flatMap((post) => post.tags))].sort((a, b) => a.localeCompare(b, 'zh-CN'));
  const years = new Set(posts.map((post) => post.date.slice(0, 4)));
  for (const file of legacy.archives) {
    const year = file.match(/^archives\/(\d{4})\//)?.[1];
    if (year) years.add(year);
  }
  add('index.html', { page: 'home' });
  for (const post of posts) add(`posts/${post.id}/index.html`, { page: 'post', post });
  add('archives/index.html', { page: 'archive' });
  for (const year of [...years].sort().reverse()) add(`archives/${year}/index.html`, { page: 'archive', year });
  add('categories/index.html', { page: 'topics' });
  add('tags/index.html', { page: 'tags' });
  for (const category of categories) add(`categories/${category}/index.html`, { page: 'home', category });
  for (const tag of tags) add(`tags/${tag}/index.html`, { page: 'home', tag });
  add('about/index.html', { page: 'about' });
  add('404.html', { page: '404' });

  const ids = new Set(posts.map((post) => post.id));
  for (const { file, id } of legacy.posts) {
    if (!ids.has(id)) throw new Error(`Legacy article points to missing post "${id}": ${file}`);
    add(file, { redirect: `posts/${id}/index.html` });
  }
  for (const file of legacy.archives) {
    if (routes.has(file)) continue;
    const year = file.match(/^archives\/(\d{4})\//)?.[1];
    add(file, { redirect: year ? `archives/${year}/index.html` : 'archives/index.html' });
  }
  const tagAliases = { '\u0043\u0047\u63d0\u53d6': 'CG', 'Live2D\u63d0\u53d6': 'Live2D', '\u538b\u7f29\u5305\u7834\u89e3': '\u538b\u7f29\u5305' };
  for (const file of legacy.tags) {
    if (routes.has(file)) continue;
    const oldTag = file.split('/')[1];
    const tag = tagAliases[oldTag] || oldTag;
    const target = tags.includes(tag) ? `tags/${tag}/index.html` : oldTag === 'Code' && categories.includes('\u5de5\u7a0b\u5b9e\u8df5') ? 'categories/\u5de5\u7a0b\u5b9e\u8df5/index.html' : 'categories/index.html';
    add(file, { redirect: target });
  }
  for (const file of legacy.categories) {
    if (routes.has(file)) continue;
    const target = file.includes('/Hexo/') && tags.includes('Hexo') ? 'tags/Hexo/index.html' : file.includes('/\u6280\u672f/') && categories.includes('\u5de5\u7a0b\u5b9e\u8df5') ? 'categories/\u5de5\u7a0b\u5b9e\u8df5/index.html' : 'categories/index.html';
    add(file, { redirect: target });
  }
  return { routes: [...routes.values()], categories, tags };
}

function redirectPage(file, target, siteUrl) {
  const relative = path.posix.relative(path.posix.dirname(file), target);
  const url = relative.split('/').map((segment) => encodeURIComponent(segment)).join('/');
  return `<!doctype html>\n<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,follow"><meta http-equiv="refresh" content="0;url=${xmlEscape(url)}"><link rel="canonical" href="${xmlEscape(new URL(target, siteUrl).href)}"><title>SLLYING</title></head><body><p><a href="${xmlEscape(url)}">\u7ee7\u7eed\u8bbf\u95ee</a></p></body></html>\n${generatedMarker}\n`;
}

function rss(site, posts) {
  const items = posts.map((post) => {
    const url = xmlEscape(new URL(`posts/${post.id}/index.html`, site.url).href);
    return `    <item>\n      <title>${xmlEscape(post.title)}</title>\n      <link>${url}</link>\n      <guid isPermaLink="true">${url}</guid>\n      <pubDate>${new Date(`${post.date}T00:00:00Z`).toUTCString()}</pubDate>\n      <description>${xmlEscape(post.excerpt)}</description>\n      <content:encoded>${xmlEscape(post.body.replace(/\b(src|href)=(['"])(?![a-z][\w+.-]*:|#|\/\/)([^'"]+)\2/gi, (_, attribute, quote, value) => `${attribute}=${quote}${new URL(value, site.url).href}${quote}`))}</content:encoded>\n${[post.category, ...post.tags].map((category) => `      <category>${xmlEscape(category)}</category>`).join('\n')}\n    </item>`;
  }).join('\n');
  const latest = posts.map((post) => post.updated || post.date).sort().at(-1);
  return `<?xml version="1.0" encoding="UTF-8"?>\n<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/">\n  <channel>\n    <title>${xmlEscape(site.name)}</title>\n    <link>${xmlEscape(site.url)}</link>\n    <description>${xmlEscape(site.description)}</description>\n    <language>zh-CN</language>\n    <atom:link href="${xmlEscape(new URL('feed.xml', site.url).href)}" rel="self" type="application/rss+xml"/>\n    <lastBuildDate>${new Date(`${latest}T00:00:00Z`).toUTCString()}</lastBuildDate>\n${items}\n  </channel>\n</rss>\n`;
}

function sitemap(site, posts, routes) {
  const latest = posts.map((post) => post.updated || post.date).sort().at(-1);
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${routes.filter((route) => !route.redirect && route.page !== '404').map((route) => `  <url><loc>${xmlEscape(new URL(route.file, site.url).href)}</loc><lastmod>${route.post?.updated || route.post?.date || latest}</lastmod></url>`).join('\n')}\n</urlset>\n`;
}

export async function buildSite({ root = projectRoot, siteUrl, render } = {}) {
  const { posts, site: inputSite } = await loadContent(root);
  const { url, previewOnly } = await resolveSiteUrl(inputSite, root, siteUrl);
  const site = { ...inputSite, url, origin: new URL(url).origin };
  const legacy = await discoverLegacyRoutes(root);
  const { routes, categories, tags } = createRoutes(posts, legacy);
  const renderPage = render || (await import(pathToFileURL(path.join(root, 'scripts/templates.mjs')).href)).renderPage;
  if (typeof renderPage !== 'function') throw new Error('scripts/templates.mjs must export renderPage(ctx).');
  const outputs = new Map();
  for (const route of routes) {
    let html = route.redirect ? redirectPage(route.file, route.redirect, site.url) : renderPage({ ...route, posts, site, base: baseFor(route.file) });
    if (typeof html !== 'string' || !/<!doctype html>/i.test(html) || !/<\/html>/i.test(html)) throw new Error(`Template did not return a complete HTML document: ${route.file}`);
    if (!html.includes(generatedMarker)) html += `\n${generatedMarker}\n`;
    outputs.set(route.file, html);
  }
  const search = posts.map(({ id, title, excerpt, category, tags: postTags, date, body }) => ({ id, title, excerpt, category, tags: postTags, date, text: plainText(body) }));
  outputs.set('js/search-index.js', `/* Generated from public article content. */\nwindow.BLOG_SEARCH = ${JSON.stringify(search).replaceAll('<', '\\u003c')};\n`);
  outputs.set('feed.xml', rss(site, posts));
  outputs.set('sitemap.xml', sitemap(site, posts, routes));
  outputs.set('robots.txt', `User-agent: *\nAllow: /\nDisallow: /scripts/\nDisallow: /tests/\nSitemap: ${new URL('sitemap.xml', site.url).href}\n`);
  const previous = JSON.parse(await readFile(path.join(root, '.site-build.json'), 'utf8').catch(() => '{"files":[]}'));
  for (const file of previous.files || []) {
    if (outputs.has(file) || !/^(?:posts|archives|categories|tags|about)\/.+\/index\.html$/.test(file)) continue;
    const absolute = insideRoot(root, file);
    const old = await readFile(absolute, 'utf8').catch(() => '');
    if (old.includes(generatedMarker)) await unlink(absolute);
  }
  for (const [file, content] of outputs) {
    const absolute = insideRoot(root, file);
    await mkdir(path.dirname(absolute), { recursive: true });
    await writeFile(absolute, content, 'utf8');
  }
  await writeFile(path.join(root, '.site-build.json'), `${JSON.stringify({ version: 1, files: [...outputs.keys()], siteUrl: site.url }, null, 2)}\n`, 'utf8');
  return { posts, site, routes, categories, tags, legacy, files: [...outputs.keys()], previewOnly };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    const result = await buildSite();
    console.log(`Built ${result.posts.length} articles and ${result.routes.length} pages in the project root.`);
    if (result.previewOnly) console.log('Feed and sitemap use a local preview URL. Set SITE_URL to the public site URL before deploying.');
  } catch (error) {
    console.error(`Build failed: ${error.message}`);
    process.exitCode = 1;
  }
}
